import json

# The perfect Cell 4 with the correct `_cleaned.csv` search and columns mapping
new_source = [
    "# Cell 4: Load Pilot Data from original cleaned CSVs\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "\n",
    "# Change to 'a' if you want to pilot Task A (literal meaning)\n",
    "PILOT_TASK = 'b'\n",
    "# Change to 1000 when you are ready to scale up\n",
    "PILOT_N = 50\n",
    "\n",
    "# FOCUSING ON 3 LANGUAGES FOR PILOT\n",
    "LANGUAGES = ['English', 'French', 'Arabic']\n",
    "\n",
    "dfs = {}\n",
    "input_dir = Path('/kaggle/input')\n",
    "if not input_dir.exists():\n",
    "    input_dir = Path('.')\n",
    "\n",
    "for lang in LANGUAGES:\n",
    "    # Look for the user's uploaded original files\n",
    "    filename = f'{lang}_cleaned.csv'\n",
    "    found_files = list(input_dir.rglob(filename))\n",
    "    \n",
    "    if found_files:\n",
    "        csv_path = found_files[0]\n",
    "        df = pd.read_csv(csv_path)\n",
    "        \n",
    "        # Standardize column names\n",
    "        col_map = {\n",
    "            'Source_Text_Yo': 'source_proverb',\n",
    "            'Source_Text_Mid': 'source_proverb',\n",
    "            'Proverb': 'source_proverb',\n",
    "            'Target_Text_En': 'proverb_en',\n",
    "            'Translation': 'proverb_en',\n",
    "            'Cultural_Context': 'correct_meaning',\n",
    "            'Correct_Meaning': 'correct_meaning'\n",
    "        }\n",
    "        df = df.rename(columns=col_map)\n",
    "        \n",
    "        # English special case: Cultural meaning IS the Translation\n",
    "        if lang == 'English' and 'correct_meaning' not in df.columns and 'proverb_en' in df.columns:\n",
    "            df['correct_meaning'] = df['proverb_en']\n",
    "            \n",
    "        required_cols = ['source_proverb', 'proverb_en', 'correct_meaning']\n",
    "        if all(c in df.columns for c in required_cols):\n",
    "            df = df.dropna(subset=required_cols).reset_index(drop=True)\n",
    "            # Ensure Sample_ID exists\n",
    "            if 'Sample_ID' not in df.columns and 'sample_id' not in df.columns:\n",
    "                df['sample_id'] = [f'{lang[:3].upper()}{str(i+1).zfill(4)}' for i in range(len(df))]\n",
    "            \n",
    "            dfs[lang] = df.sample(min(PILOT_N, len(df)), random_state=42)\n",
    "            print(f\"✅ {lang}: Loaded {len(dfs[lang])} items from {csv_path.name}\")\n",
    "        else:\n",
    "            missing = [c for c in required_cols if c not in df.columns]\n",
    "            print(f\"❌ {lang}: Found file but missing columns: {missing}. Available: {list(df.columns)}\")\n",
    "    else:\n",
    "        print(f\"❌ {lang}: File {filename} not found anywhere in /kaggle/input\")\n"
]

# We need a fallback check so we don't crash the audit step if dfs is empty
new_audit_source = [
    "# Cell 6: Shortcut Resistance Score (SRS) Audit\n",
    "if len(gen_rows) == 0:\n",
    "    print('❌ Skipping Audit: No data generated because CSV files were not found.')\n",
    "else:\n",
    "    print('=== BLIND SHORTCUT AUDIT ===')\n",
    "    AUDIT_SYS = (\n",
    "        'You are answering a multiple-choice question about a proverb. '\n",
    "        'Select the option that best matches the question. '\n",
    "        'Reply with ONLY the letter: A, B, C, or D.'\n",
    "    )\n",
    "    AUDIT_Q = {\n",
    "        'a': 'What does this proverb most likely mean literally?',\n",
    "        'b': 'Which option best captures the cultural meaning of this proverb?',\n",
    "    }\n",
    "\n",
    "    def audit_prompt(task, proverb, translation, ca, cb, cc, cd):\n",
    "        return (\n",
    "            f'Proverb: {proverb}\\nEnglish: {translation}\\n\\n'\n",
    "            f'{AUDIT_Q[task]}\\nA. {ca}\\nB. {cb}\\nC. {cc}\\nD. {cd}\\n\\nAnswer (A/B/C/D only):'\n",
    "        )\n",
    "\n",
    "    audit_rows = []\n",
    "    for i, row in gen_df.iterrows():\n",
    "        ap = audit_prompt(\n",
    "            PILOT_TASK, row['source_proverb'], row['proverb_en'],\n",
    "            row['Choice_A'], row['Choice_B'], row['Choice_C'], row['Choice_D']\n",
    "        )\n",
    "        raw = run_audit(AUDIT_SYS, ap)\n",
    "        raw = (raw or '').strip().upper()\n",
    "        pred = None\n",
    "        for ch in 'ABCD':\n",
    "            if raw.startswith(ch): pred = ch; break\n",
    "        if not pred:\n",
    "            import re\n",
    "            m = re.search(r'\\b([ABCD])\\b', raw)\n",
    "            pred = m.group(1) if m else None\n",
    "            \n",
    "        audit_rows.append({\n",
    "            'language': row['language'],\n",
    "            'sample_id': row['sample_id'],\n",
    "            'correct': row['Answer'],\n",
    "            'predicted': pred,\n",
    "            'is_correct': int(pred == row['Answer']) if pred else 0,\n",
    "        })\n",
    "        \n",
    "        if (i+1) % 20 == 0:\n",
    "            print(f\"  Audited {i+1}/{len(gen_df)}...\")\n",
    "\n",
    "    audit_df = pd.DataFrame(audit_rows)\n",
    "    audit_path = OUT_DIR / f'pilot_v2_audit_{PILOT_TASK}.csv'\n",
    "    audit_df.to_csv(audit_path, index=False)\n",
    "\n",
    "    print('\\n=== SHORTCUT RESISTANCE SCORE (SRS) ===')\n",
    "    print(f'{\"Language\":<12} {\"N\":>5} {\"Acc% (SRS)\":>12} {\"vs 25%\":>9} {\"Status\":>12}')\n",
    "    print('-'*55)\n",
    "    all_pass = True\n",
    "    for lang in LANGUAGES:\n",
    "        sub = audit_df[audit_df['language']==lang]\n",
    "        if len(sub)==0: continue\n",
    "        acc = round(sub['is_correct'].mean()*100, 1)\n",
    "        delta = acc - 25.0\n",
    "        status = '✅ PASS' if acc < 40 else ('🟡 REVIEW' if acc < 55 else '🔴 FAIL')\n",
    "        if acc >= 40: all_pass = False\n",
    "        print(f'{lang:<12} {len(sub):>5} {acc:>10.1f}% {delta:>+8.1f}pp {status:>12}')\n",
    "\n",
    "    overall = round(audit_df['is_correct'].mean()*100, 1)\n",
    "    print('-'*55)\n",
    "    print(f'{\"OVERALL\":<12} {len(audit_df):>5} {overall:>10.1f}%')\n",
    "    print(f'\\nTarget SRS: < 40% (Closer to 25% is better)')\n",
    "    print(f'Verdict: {\"✅ READY TO SCALE\" if all_pass else \"🔴 NEEDS MORE WORK\"}')\n"
]

with open("C:\\Users\\User\\Downloads\\THe proverbeval container\\MCQ\\proverbgap-pilot-v2.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and cell['source'] and '# Cell 4: Load Pilot Data' in cell['source'][0]:
        cell['source'] = new_source
    if cell['cell_type'] == 'code' and cell['source'] and '# Cell 6: Shortcut Resistance Score (SRS) Audit' in cell['source'][0]:
        cell['source'] = new_audit_source

with open("C:\\Users\\User\\Downloads\\THe proverbeval container\\MCQ\\proverbgap-pilot-v2.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
